### ISSUE TITLE
Unclear if flipping of PNG/TGA really not needed for KSP 1.0+

### ISSUE THREAD

**Issue by ghost** [Telanor/DDS4KSP#3]
HI Telanor,
I am sorry, I might have sent you the pull request too early.
I only just noticed that with my fully converted mod array, there are indeed some weird texture issues with _some_ mods (especially those from UmbraSpaceIndustries). 
I am currently analyzing whether flipping of PNG/TGA can really be omitted on KSP 1.0, or not.
Might have to set the default of the checkbox to true...
Cheers,
TheDog

**Comment by Telanor** [comment]
Ok, well let me know.  I don't really have any parts mods anymore so I haven't really had to do any converting since the stock parts are dds now.

**Comment by ghost** [comment]
Alright, consider this issue closed:
apparently KSP 1.0+ still needs DDS textures to be flipped, so I left the option in the dialog, but set the default to flipping = true.
New pull request will come in a minute...
